Разметка главной страницы
htmlacademy-htmlcss/1591735-sedona-29 pull request #2
Opened 2020-10-08 14:48 UTC by wellamko

2020-10-09 06:47 UTC, mkolotovich requested changes
Исправь замечания

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +          <li><a href="blank.html">Карта штата</a></li>
Согласно заданию - Ссылки должны быть размечены правильно: ссылки на существующие страницы вести на них <a href="catalog.html">, ссылки на несуществующие страницы оставаться пустыми <a href="">. Оставь здесь пустые ссылки.

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +
Пропустила блок с изображением гор. Добавь его

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +  <h2>Преимущества</h2>
Этого заголовка нет в макете. Таким заголовкам задавай класс visually hidden.

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +<p>1 - Седона - не аттракцион для туристов, там течёт своя жизнь</p>
Здесь и далее пропустила — №. Вынеси текст — №1 — в отдельный элеменет для удобства стилизации. Тоже самое проделай и для других элементов списка.

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +</li>
Добавь второй элемент списка с фото.

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +  <dt>Сувениры</dt>
Оберни названия терминов в b или strong

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +<li>
Добавь фото

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +  <!-- Здесь будет карта -->
Вставь изображение-заглушку под карту. По заданию - Используйте вместо них заглушки, например: <img src="https://via.placeholder.com/150x100" alt="">, где 150x100 в адресе картинки — это её размер.

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +    <section>
По спецификации тег section подразумевает использовани заголовка. Если заголовка у блока нет, то можешь его не использовать, а сразу делать список.

2020-10-09 06:47 UTC, mkolotovich commented on index.html
> +    <a href="https://htmlacademy.ru">HTML Academy</a>
Согласно ТЗ(https://up.htmlacademy.ru/htmlcss/29/project/sedona#sedona-3-8)-3.8. Логотип Академии в подвале ведёт на лендинг интенсива «HTML и CSS. Профессиональная вёрстка сайтов». И добавь заглушку для логотипа академии.

2020-10-09 12:30 UTC, wellamko commented on index.html
> +          <li><a href="blank.html">Карта штата</a></li>
<li><a href="#">Информация</a></li>
          <li><a href="#">Фото и видео</a></li>
          <li><a href="#">Карта штата</a></li>

2020-10-09 12:30 UTC, wellamko commented on index.html
> +
<img src="img/background photo.jpg" width="1200" height="509" alt="Горы">

2020-10-10 15:32 UTC, mkolotovich commented on index.html
> +
Блок с горами я тебе писал вставить ниже шапки. Изображение гор это фоновое изображение, его нужно вставлять через стили. А изображениe welcome to the gorgeous sedona because the grand canyon sucks - это контентное изображение.

2020-10-10 15:38 UTC, mkolotovich commented on index.html
> +</li>
Если ты не добавляешь второй элемент списка, то оберни заголовок и два параграфа в див, чтобы это можно раскидать флексом как на макете.

2020-10-10 15:39 UTC, mkolotovich commented on index.html
> +<li>
Здесь сделай тоже самое как я писал тебе выше. Если ты не добавляешь второй элемент списка, то оберни заголовок и два параграфа в див, чтобы это можно раскидать флексом как на макете.

2020-10-10 15:41 UTC, mkolotovich commented on index.html
> +  <!-- Здесь будет карта -->
Размер изображения с картой по макету не 150x100. Укажи размер фото как на макете.

2020-10-10 15:49 UTC, mkolotovich commented on index.html
> +    <section>
Ты немного не так сделала, как я имел ввиду. Вынеси из секции на уровень вверх список и параграф, чтобы это можно было раскидать флексом для сеток.

2020-10-10 15:51 UTC, mkolotovich requested changes
Исправь замечания не исправленные с прошлой проверки (я к ним оставил комментарий).

2020-10-14 06:20 UTC, mkolotovich commented on index.html
> +
Молодец изображение гор ты вставила ниже шапки как я и писал, но я писал блок, т.е. блочный элемент, например див, а ты зачем-то вставила ссылку. И я же тебе писал, что изображение гор - это фоновое изображение и его нужно вставлять через стили, а ты его вставляешь через разметку. А вот то что необходимо вставить через разметку изображениe welcome to the gorgeous sedona because the grand canyon sucks ты как раз и не вставила.

2020-10-14 06:22 UTC, mkolotovich commented on index.html
> +</li>
Я тебе написал как сделать, а ты вместо этого зачем-то оборачиваешь в ссылку фоновое изображение. Вопрос, зачем? Фоновое изображени вставляется через стили. Это раз. А во-вторых зачем тут ссылку. Я же говорил обернуть в див, а не в ссылку и не изображение, а загловок и два параграфа.

2020-10-14 06:22 UTC, mkolotovich commented on index.html
> +<li>
Я тебе написал как сделать, а ты вместо этого зачем-то оборачиваешь в ссылку фоновое изображение. Вопрос, зачем? Фоновое изображени вставляется через стили. Это раз. А во-вторых зачем тут ссылку. Я же говорил обернуть в див, а не в ссылку и не изображение, а загловок и два параграфа.

2020-10-14 06:23 UTC, mkolotovich requested changes
Исправь 3 замечания с первой проверки(я к ним оставил комментарии) и мердж. Что не понятно спрашивай в телеграмме.

2020-10-14 07:47 UTC, merged